name: hw2
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - h5py
  - matplotlib
  - jupyter
  - pytorch
  - torchvision
  - cpuonly  # GPU 없는 경우
  - scikit-image
  - nltk
  - pip:
      - tqdm
